Weed-AI/Weed-AI

- .github/workflows/validate_json.yml
Demonstrating the possibility of end-to-end testing referenced in https://github.com/Sydney-Informatics-Hub/Weed-ID-Interchange/pull/42#issuecomment-681807326.
> Generate deepweeds and cwfid Weed COCO JSON in CI

- .github/workflows/validate_json.yml
- conversion_tools/cwfid_to_json/cwfid_imageinfo.json
- conversion_tools/cwfid_to_json/cwfid_to_json.py
- conversion_tools/deepweeds_to_json/deepweeds_to_json.py
> Test the Weed COCOs stored in git

- conversion_tools/draft export to elastic.py
Needed if it seems reactivesearch struggles with nested paths
Before it had nested things like this:
```json
{
"id": 20,
"file_name": "cwfid_images/020_image.png",
"license": 0,
"agcontext_id": 0,
"width": 1296,
"height": 966,
"resolution": 1251936,
"annotations": [
{
"id": 488,
"image_id": 20,
"category_id": 0,
"segmentation": [
[
807,
563,
695,
635,
694,
671,
816,
741,
842,
713,
849,
663,
821,
564
]
],
"iscrowd": 0,
"category": {
"common_name": "carrot",
"species": "daugus carota",
"eppo_taxon_code": "DAUCS",
"eppo_nontaxon_code": "3UMRC",
"role": "crop",
"id": 0
},
"agcontext": {
"id": 0,
"agcontext_name": "cwfid",
"crop_type": "other",
"bbch_descriptive_text": "leaf development",
"bbch_code": "GS10-19",
"grains_descriptive_text": "seedling",
"soil_colour": "grey",
"surface_cover": …
```
> Flatten indexed objects

- search/src/App.js
Good changes, happy to bring this in straight away.
> Small tweaks to display

- search/package.json
- search/yarn.lock
Responding to a dependabot alert
> Upgrade node-forge, node-fetch and other dependencies with conflicts

- .github/workflows/validate_json.yml
- search/src/App.js
- weedcoco/cwfid_to_json/cwfid_imageinfo.json
- weedcoco/importers/cwfid.py
- weedcoco/importers/deepweeds.py
- weedcoco/schema/Category.yaml
- weedcoco/schema/main.yaml
Fixes #83
Fixes #57
Helps towards specifying categories in importers (#33, #34)
> WeedCOCO category names are now a combination of role and species

- weedcoco/schema/Image.yaml
> Don't require license for each image

- search/docker-compose.yml
> dejavu removal

- search/src/Components/reactive_search.js
This creates the separate file of reactive search for routing
> separate file for reactive_search.js

- search/scripts/download_test_thumbnails.sh
- search/scripts/load_data_from_rds.sh
- search/scripts/weedcoco_to_elastic_index_bulk.py
added in more datasets to the bulk load/setup script
> Load more data

- weedcoco/index/indexing.py
Try to debug CI failure with hosts.
> Fix ElasticSearch constructor

- search/src/Components/wrapper/upload.js
> Readable upload status

- conftest.py
- weedcoco/tests/repo/test_deposit.py
> Make it easier to test deposit with changing data

- search/src/Components/wrapper/navbar.js
> Support Open in New Tab for navbar

- search/src/Components/forms/AgContextForm.js
- search/src/Components/forms/MetadataForm.js
- search/src/Components/upload/upload_stepper.js
> Disable Next button when form doesn't validate

- search/django/weedid/utils.py
- search/django/weedid/views.py
- search/src/Components/dataset/dataset_list.js
> show contributor email in awaiting dataset list

- search/src/Components/wrapper/reactive_search.js
- weedcoco/index/indexing.py
- weedcoco/tests/index/test_indexing.py
Fixes #257 
Fixes #258
Fixes #256
> Small improvements to result card

- search/src/Components/wrapper/reactive_search.js
> relabel 'Clear All' to 'Clear Filters'

- search/src/Schemas/AgContext.json
- weedcoco/cwfid_to_json/cwfid_imageinfo.json
- weedcoco/importers/cwfid.py
- weedcoco/index/indexing.py
- weedcoco/schema/AgContext.yaml
- weedcoco/tests/index/test_indexing.py
- weedcoco/tests/repo/deposit_data/basic_1/weedcoco.json
- weedcoco/tests/repo/deposit_data/basic_2/weedcoco.json
- weedcoco/tests/repo/deposit_data/duplicate/weedcoco.json
- weedcoco/tests/repo/deposit_data_sample/basic/dataset_1/weedcoco.json
- weedcoco/tests/repo/deposit_data_sample/multiple/dataset_1/weedcoco.json
- weedcoco/tests/repo/deposit_data_sample/multiple/dataset_2/weedcoco.json
- weedcoco/tests/test_stats.py
- weedcoco/tests/test_validation.py
> growth range is now an object with two properties

- weedcoco/schema/Image.yaml
The current one is not standard JSON Schema
> Fix Image.date_captured type spec

- .github/workflows/frontend.yml
- .github/workflows/pytest.yml
Making sure that installation is correct, not just local repository module
> Test from installation rather than local source

- weedcoco/importers/mask.py
- weedcoco/tests/importers/test_mask.py
> Support importing masks where not all images have annotations

- .github/workflows/pytest.yml
This reverts commit f448dad72742a186f39537290e6ec0facf2b0628.
> Revert "Test from installation rather than local source (#229)"

- weedcoco/stats.py
- weedcoco/tests/test_stats.py
> Fix some poor defensive programming in weedcoco.stats

- search/django/weedid/models.py
- search/django/weedid/tasks.py
- search/django/weedid/views.py
> Print tracebacks in celery tasks; store whole status details

- search/src/Components/upload/react-images-upload/index.js
Nothing major, just updated the text 'Max file size: 5mb, accepted: jpg|gif|png'
> updated upload text for image size/acceptable types

- weedcoco/index/indexing.py
> Use a fixed elasticsearch ID for each image so that repeated indexing overwrites

- search/django/weedid/views.py
> fix #161 allowing only limited elastic requests to be passed through

- search/src/Components/wrapper/reactive_search.js
This commit seems to have been lost last week...
> Show task type in result card

- search/src/Components/dataset/dataset_list.js
- search/src/Components/dataset/dataset_summary.js
> Fix display of bbch_growth_range, and hide dummy details from dataset_list

- search/src/Components/wrapper/navbar.js
- search/src/Components/wrapper/reactive_search.js
Fixes #300
Known issue: footer doesn't fill the whole width when there are few images displayed.
> An attempt to put the footer in a better place on the Explore page

- search/src/Components/wrapper/navbar.js
> Show editor buttons on mobile view menu

- search/django/Dockerfile
- search/django/Dockerfile-dev
- search/django/requirements.txt
- search/docker-compose-dev.yml
- search/docker-compose.yml
Also allow change of weedcoco version/tag in .env
> Rebuild when weedcoco master has changed

- search/src/Components/forms/AgContextForm.js
- search/src/Schemas/AgContext.json
- weedcoco/schema/AgContext.yaml
> Make cropped_to_plant false by default

- search/django/core/settings.py
- search/django/weedid/templates/sitemap.xml
- search/django/weedid/urls.py
- search/django/weedid/views.py
- search/nginx/nginx/nginx.conf
Fixes #255
I'm keen to give search engines a chance to properly index the site, and so to deploy the SEO stuff ASAP
> Serve sitemap.xml from Django

- search/django/core/settings.py
- search/docker-compose-dev.yml
- search/docker-compose.yml
I suspect this has been the issue blocking me from launching a dev environment.
> Ensure consistent postgres credentials in docker and django

- search/src/Components/dataset/dataset_summary.js
> Add description boilerplate

- search/src/Components/wrapper/reactive_search.js
> move dataset filter to right

- search/src/App.js
- search/src/Components/wrapper/reactive_search.js
> Show weed species on result card instead of just 'weed' or 'crop'

- search/src/Schemas/Metadata.json
- weedcoco/schema/Metadata.yaml
> Qualify "Name" in Metadata editor

- search/src/Components/dataset/dataset_summary.js
Fixes #353
(By default the Citation and Licensing accordion is closed.)
> Improve display of citation data on dataset summary

- weedcoco/tests/index/test_indexing.py
- weedcoco/utils.py
> Empty segmentation is not segmentation

- search/django/weedid/utils.py
> Coco must be saved at weedcoco.json currently

- search/src/Components/formRenderers/OneOfRenderer.tsx
- search/src/Components/formRenderers/default_renderers.tsx
- search/src/Components/forms/AgContextForm.js
- search/src/Components/forms/MetadataForm.js
- search/src/Schemas/AgContext.json
- weedcoco/schema/AgContext.yaml
- title displayed, fixes #394
- tab space indented
Towards #397
> Improved jsonforms rendering of oneOf controls

- search/src/Components/wrapper/about.js
- search/src/Components/wrapper/navbar.js
- search/src/Components/wrapper/privacy.js
- search/src/Components/wrapper/upload.js
- search/src/Components/wrapper/weedcoco.js
- search/src/styles/common.js
Not strictly at the top of our priorities, but might improve SEO (not as much as server-side rendering would).
> Improve mobile styling for articles: smaller margins, larger font

- search/src/Components/wrapper/about.md
How does this look for a temporary citation, @geezacoleman??
> Add a temporary citation form

- search/src/Components/upload/react-images-upload/index.js
- search/src/Components/upload/uploader_images.js
> avoid overlapping image and file name

- .github/workflows/jest.yml
- search/src/App.test.js
- search/src/Components/wrapper/navbar.js
Fix some small errors along the way
> Add jest CI

- weedcoco/validation.py
Apparently dates with XXs were being passed before only because `format: date` was being ignored. Now that `format_checker` is used, this change is needed.
Extracted from #420
> Fix date validation

- search/package.json
- search/src/Components/formRenderers/ConstRenderer.tsx
- search/src/Components/formRenderers/default_renderers.tsx
- search/src/Components/forms/MetadataForm.js
- search/src/Components/upload/upload_stepper.js
- search/yarn.lock
Issue was due to the implementation of ConstRenderer, which did not correctly imploy 'effects'
The other changes in this PR are not essential.
A remaining issue after this fix is the slow responsiveness when entering text in the form, I think due to the upload/editor button..?
> Fix issue where meta editor resulted in infinite recursion

- search/package.json
- search/src/Common/Markdown.js
- search/src/Components/dataset/dataset_summary.js
- search/src/Components/error/details.js
- search/src/Components/wrapper/about.js
- search/src/Components/wrapper/privacy.js
- search/src/Components/wrapper/upload.js
- search/src/Components/wrapper/upload.md
- search/src/Components/wrapper/weedcoco.js
- search/src/styles/common.js
- search/yarn.lock
> DOC document supported upload formats

- search/django/Dockerfile
- search/docker-compose.yml
- search/nginx/mystatic/Dockerfile
- search/nginx/mystatic/nginx.conf
- search/nginx/nginx/nginx.conf
> add gunicorn and static file server for mystatic

- search/src/Components/dataset/dataset_summary.fixture.js
- search/src/Components/dataset/dataset_summary.js
This is one of a few cosmetic changes I've played with in spare moments.
Fixes #484
The descriptions could be improved, but wdyt @geezacoleman ?
(natural is expanded because the mouse is over it)
> AgContext styling in dataset summary

- weedcoco/species_utils.py
- weedcoco/tests/test_species_utils.py
This may fix your local issues @ElevnLi
> EPPO: Unlink and retry when cached file is broken

- setup.py
> Pin elastic search client to latest supporting elasticsearch-oss docker

- search/src/Schemas/AgContext.json
- weedcoco/schema/AgContext.yaml
> Allow negative longitude

- search/src/Components/wrapper/upload.md
> add to excluded images list

- search/src/Components/upload/uploader_category_mapper.js
> Left margin on text_field in category mapping ui

- search/docker-compose.yml
> Upgrade the elasticsearch version to mitigate log4shell

- search/django/core/settings.py
- search/django/weedid/utils.py
- search/docker-compose-dev.yml
Minor bug fix - os.environ.get("SEND_EMAIL", True) meant that you couldn't pass a false value and turn off email notifications in dev
> Bugfix: send email

- README.md
- search/src/Components/search/CategoryTooltip.js
- search/src/Components/search/ResultCard.js
- search/src/Components/upload/uploader_category_mapper.js
- search/src/Components/wrapper/about.js
- search/src/Components/wrapper/reactive_search.js
- search/src/Components/wrapper/upload.md
- search/src/Components/wrapper/weedcoco.md
- search/src/Schemas/AgContext.json
- weedcoco/schema/AgContext.yaml
- weedcoco/schema/Category.yaml
- weedcoco/utils.py
- weedcoco/validation.py
Perhaps the code changes here go further than they need to... Would one of you like to review?
Fixes #582
> Improve documentation and code for non-species categories

- search/django/weedid/tus.py
- search/django/weedid/urls.py
tus uploads work on localhost, but that's not what this fix is trying to solve.
Any suggestions for a simple way to test https termination on localhost?
> new TusProxy middleware to rewrite Location

- search/docker-compose.yml
@ElevnLi do you recall why there had been no logging here?
> reverse proxy needs a log

- search/src/Components/upload/react-images-upload/index.js
change text to "No preview available over {preview_maximum} images"
> update preview text wording

- search/django/weedid/views.py
> Stop raising exceptions in an unexceptional upload_status

- search/docker-compose.yml
Fixed one line in docker compose, to enable auto restart for tus.
> config tus to restart when docker does

- search/README.md
Add more instructions to make onboarding and setup easier.
> Instructions hotfix

- search/README.md
- search/src/Components/wrapper/annotate.js
- search/src/Components/wrapper/navbar.js
Add annotation tab to front end.
> Annotation Tab (#695)
